services:
  db:
    image: postgres:15
    container_name: portfolio_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paswordik
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: portfolio_app
    depends_on:
      - db
    ports:
      - "8501:8501" # Streamlit default port
    environment:
      - DATABASE_URL=postgresql://postgres:paswordik@db:5432/portfolio_db
    volumes:
      - .:/app # Optional: mounts your code for live updates

volumes:
  postgres_data: